[opensuse-tumbleweed]
image=localhost/opensuse-tumbleweed-template
hostname=opensuse-tumbleweed
start_now=true
# Export
exported_bins_path="/home/tie/.local/bin"
exported_bins="/usr/bin/git /usr/bin/nvim /usr/bin/stow /usr/bin/tree /usr/bin/yt-dlp"
