[dominion-box]
additional_packages="curl git gh make neovim nodejs24 npm24 stow tree"
image=registry.opensuse.org/opensuse/tumbleweed:latest
init=true
home=${HOME}/dominion
replace=false
root=false

# Install Thaifont
init_hooks=zypper repos | grep -q M17N_fonts || zypper --non-interactive addrepo --no-gpgcheck --refresh https://download.opensuse.org/repositories/M17N:fonts/openSUSE_Tumbleweed/M17N:fonts.repo;
init_hooks=zypper --non-interactive install thai-fonts;

# Install VSCode
init_hooks=[ ! -f "${HOME}/code.rpm" ] && curl -o code.rpm https://vscode.download.prss.microsoft.com/dbazure/download/stable/e7fb5e96c0730b9deb70b33781f98e2f35975036/code-1.114.0-1775036339.el8.x86_64.rpm;
init_hooks=zypper --non-interactive --no-gpg-checks install "${HOME}/code.rpm";

# Install pnpm
init_hooks=npm install -g pnpm@latest-10;
